substitutions:
  devicename: open-air-valve-huis-2
  upper_devicename: "Huis Valve 2 Master Bedroom"

packages:
  config: !include config.yaml
  hardware: !include ../shared/Open_AIR_Valve_DIS_SCD40.yaml

esphome:
  includes:
    - ../shared/local_mode_helpers.h
