substitutions:
  devicename: open-air-valve-huis-1
  upper_devicename: "Huis Valve 1 Bathroom"

packages:
  config: !include config.yaml
  hardware: !include ../shared/Open_AIR_Valve_DIS_SHT4x.yaml

esphome:
  includes:
    - ../shared/local_mode_helpers.h
