substitutions:
  devicename: open-air-valve-huis-3
  upper_devicename: "Huis Valve 3 Toilet"

packages:
  config: !include config.yaml
  hardware: !include ../shared/Open_AIR_Valve_DIS_SCD40_SGP41.yaml

esphome:
  includes:
    - ../shared/local_mode_helpers.h
