substitutions:
  devicename: garage-valve-4
  upper_devicename: Garage Valve 4

packages:
  config: !include config.yaml
  hardware: !include ../shared/Open_AIR_Valve_DIS_SCD40_SGP41.yaml

esphome:
  includes:
    - ../shared/local_mode_helpers.h
