substitutions:
  devicename: open-air-valve-1
  upper_devicename: Open AIR Valve 1

packages:
  config: !include config.yaml
  hardware: !include ../shared/Open_AIR_Valve_DIS_SCD40_SGP41.yaml

esphome:
  includes:
    - ../shared/local_mode_helpers.h
